### ISSUE TITLE
Add Slack notification plugin

### ISSUE THREAD

**Issue by arnobaer** [hephy-dd/sqc#17]
Add a Slack notification function to notify using Slack [Webhooks](https://api.slack.com/messaging/webhooks) when measurements finished.

This requires to add an input field in a preferences dialog to enter a custom Slack Webhooks URL to be used to send the notification.

**Comment by schultschikhephy** [comment]
always include the sensor number
post notification for good or bad microscope inspection including a heros link to the images
post notification for ETA once the measurement has started 
post notification once measurement is finished 
include a summary of the measurement including a picture of the IV/CV and stripscan plots

**Comment by arnobaer** [comment]
> * always include the sensor number

:white_check_mark: This can be done, together with additional sensor meta data.

> * post notification for good or bad microscope inspection including a heros link to the images

:x: Linking to the output location of the images by using an URL is not possible as it can be either a local drive or a mounted remote drive accessible only on the machine running the software. Not sure about how to define _good_ and _bad_ optical scans?

> * post notification for ETA once the measurement has started

:x: This is quite tricky. Depending on the individual selection of measurements and intervals it might take some time until a reliable ETA can be calculated. An alternative would be to publish ETAs in regular intervals but this might produce a lot of unwanted messages in the channel.

> * post notification once measurement is finished

:white_check_mark: This can be done, together with statistics about the measurements.

> * include a summary of the measurement including a picture of the IV/CV and stripscan plots

:x: Using Slack Webhooks it is not possible to publish attachments like images or documents.

> * post a notification if 5 consecutive strips (either strip or interstrip measurements) have been remeasured, so we can have a look and potentially stop the measurement.

:white_check_mark: This can be done. Maybe by specifying a threshold for re-measure count in the preferences.

**Comment by arnobaer** [comment]
Proposal for user configurable notification messages with placeholders for sensor and other information.

![notification-plugin](https://github.com/hephy-dd/sqc/assets/3717588/30ada7e1-fc2f-4c54-ba93-15414894a803)
