### ISSUE TITLE
strip remeasurement: change input method

### ISSUE THREAD

**Issue by schultschikhephy** [hephy-dd/sqc#26]
when inputting strips for remeasurement, no popup window, because it prevents from using the plots and checking which strip numbers. rather an input field at the bottom of the sequence window that is emptied after every run and after every remeasurement

**Comment by arnobaer** [comment]
There is need for an auto-selection tool of _bad_ strips. Select strips that either:
- had been re-measured at least _n_ times for any measurement
- had failed all re-measure attempts for any measurement
