### ISSUE TITLE
Controlling flashing light

### ISSUE THREAD

**Issue by schultschikhephy** [hephy-dd/sqc#40]
Hi, ich hatte gerade das Problem, dass jemand die SQC geöffnet hat, während die optische Inspektion gerade fertig wurde, weil das Licht nicht blinkte. Könntest du das so machen, dass das Licht so lange blinkt, so lange das Feld für die optische Inspektion geöffnet ist, und sobald es geschlossen wird, soll die Lampe noch für 60minuten weiter blinken, damit ich genug zeit habe um die Messung zu starten. Und weiterhin während der Messung natürlich auch.

**Comment by arnobaer** [comment]
I need to think a about a more robust implementation. As a first try I can add a _Keep light flashing after scan_ check box so that whatever time will pass until the measurement the blinker will continue flashing until closing the alignment dialog.

**Comment by arnobaer** [comment]
In addition I'm adding an action to manually toggle the flashing light in the main window. This permits the operator to manually toggle the flashing light when not in a measurement. A measurement always enables the flashing light and disables it on finish.

![Screenshot from 2024-01-24 15-27-02](https://github.com/hephy-dd/sqc/assets/3717588/d1e5d9fa-9572-4df6-a844-281e847d7944)

Now when running the optical scan and checking option  _Keep light flashing after scan_ in the dialog, the light will keep flashing a) until the operator closes all dialogs and switches it off in the main window or b) after the next measurement finishes.
