### ISSUE TITLE
add switching scheme

### ISSUE THREAD

**Issue by schultschikhephy** [hephy-dd/sqc#41]
Könntest du bitte dieses Bild vom Switching scheme von der Software aus aufrufbar machen? Es sollte halt auch Möglich sein, dass wir die Bilddatei gegen eine neuere Version austauschen. Aber dann hätten wir immer die aktuelle Version aufrufbar. Am Desktop zB liegen nur veraltete Versionen.

**Comment by arnobaer** [comment]
The current switching scheme is already part of the online documentation and can be updated on github (main branch) at without requiring a software change. The file in question is located here: https://github.com/hephy-dd/sqc/tree/main/docs/assets

In the current version of the software either _Help_ -> _Contents_ or hitting _F1_ opens a browser to the github repository (https://github.com/hephy-dd/sqc) where the switching scheme is also displayed in the readme. The link to the online documentation is located in the sidebar.

What I can improve is redirecting _Help_ -> _Contents_ and hitting _F1_ to open the online documentation and adding an additional GitHub action to the help menu to also access the github repository.
